### ISSUE TITLE
Still maintained? 4.5 release planned?

### ISSUE THREAD

**Issue by JoeMurray** [mc0e/civicrm-extendedmailingstats#2]
Heh @mc0e, for an alpha extension listed as only 4.2 compatible the fact that it has 18 installations is pretty great. At JMA we've put out the Mandrill Transactional Email extension and now we are working on a Mandrill CiviMail one for 4.4 and 4.5. If you are planning on making this available for 4.4 or 4.5 we'd want to make sure out extension works with it. Do you know if it works in 4.4/4.5, or have any plans to do a new release?

**Comment by mc0e** [comment]
Sorry Joe, I hadn't seen your message till just now.

The client I developed this for is currently running CiviCRM 4.4, an no issues have been brought to my attention.

**Comment by eileenmcnaughton** [comment]
Hi Joe,

I've just had a quick look on 4.6 & seems to run OK

**Comment by JoeMurray** [comment]
Thanks!

Joe Murray, PhD
President, JMA Consulting
joe.murray@jmaconsulting.biz
skype JosephPMurray twitter JoeMurray
416.466.1281

On Sun, Feb 8, 2015 at 10:03 PM, Eileen McNaughton <notifications@github.com
